# Generated by Django 5.2.6 on 2025-09-24 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSend',
            fields=[
                ('reg_no', models.AutoField(primary_key=True, serialize=False, verbose_name='เลขทะเบียนส่ง')),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='ที่')),
                ('date', models.DateField(verbose_name='ลงวันที่')),
                ('sender', models.CharField(max_length=200, verbose_name='จาก')),
                ('receiver', models.CharField(max_length=200, verbose_name='ถึง')),
                ('subject', models.CharField(max_length=300, verbose_name='เรื่อง')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='การปฏิบัติ')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'ทะเบียนหนังสือส่ง',
                'verbose_name_plural': 'ทะเบียนหนังสือส่ง',
                'ordering': ['-date', '-reg_no'],
            },
        ),
    ]
